**Glosario de Kubernetes Fundamentals (Inglés - Español)**

| **Término en Inglés** | **Traducción al Español** | **Breve Explicación en Español** |
|-------------------------------|-----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **API Server** | **Servidor de la API** | El componente central de control de Kubernetes. Expone la API de Kubernetes, permitiendo a los usuarios, la línea de comandos (`kubectl`), y otros componentes comunicarse con el clúster.                                                                                                                                                                                          |
| **Cluster** | **Clúster** | Un conjunto de nodos que ejecutan aplicaciones en contenedores gestionados por Kubernetes.                                                                                                                                                                                                                                                                                       |
| **Container** | **Contenedor** | Una unidad de software estandarizada que empaqueta código, dependencias y configuraciones, permitiendo que las aplicaciones se ejecuten de manera rápida y fiable en diferentes entornos. Docker es una tecnología de contenedores popular.                                                                                                                                         |
| **Control Plane** | **Plano de Control** | El conjunto de componentes que gestionan el clúster. Incluye el API Server, etcd, kube-scheduler, kube-controller-manager y kubelet (en el nodo maestro).                                                                                                                                                                                                                         |
| **etcd** | **etcd** | Un almacén de valores clave distribuido y altamente disponible utilizado por Kubernetes para almacenar todos los datos de configuración del clúster.                                                                                                                                                                                                                                |
| **kubectl** | **kubectl** | La herramienta de línea de comandos de Kubernetes que permite a los usuarios interactuar con el API Server para gestionar el clúster.                                                                                                                                                                                                                                            |
| **Kubelet** | **Kubelet** | Un agente que se ejecuta en cada nodo del clúster. Es responsable de asegurar que los contenedores estén corriendo en un Pod. Se comunica con el Control Plane.                                                                                                                                                                                                                    |
| **Kube-proxy** | **Kube-proxy** | Un proxy de red que se ejecuta en cada nodo. Implementa las reglas de red que permiten la comunicación con los Pods desde dentro o fuera del clúster.                                                                                                                                                                                                                         |
| **Node** | **Nodo** | Una máquina física o virtual donde se ejecutan los contenedores. Los nodos son gestionados por el Control Plane.                                                                                                                                                                                                                                                                   |
| **Pod** | **Pod** | La unidad básica desplegable en Kubernetes. Un Pod puede contener uno o más contenedores que están estrechamente relacionados y comparten recursos (como red y almacenamiento). 
